### ISSUE TITLE
Тексты

### ISSUE THREAD

**Issue by butkam** [nomorespellingerrors/teledit#12]
Хорошие новости: мы выполним ваш заказ в течение 25 минут после оплаты заказа.

Стоимость: 16,50 грн.

Чтобы подтвердить и оплатить заказ, перейдите по этой ссылке: http://correctarium.com/payment/telegram/e4afc7fd25182c397118f6690189f7ea

***

Anton Poliakov (@antonpoliakov) разместил заказ на редактуру/корректуру.
Идентификатор заказа: #e4afc7fd25182c397118f6690189f7ea

Символов c пробелами: 10
Оплачено: 16,50 грн.
Нужно сдать через 25 минут

Текст:

> Текст заказа

***

#### Текст ошибки

Я знаю две команды: /proof для корректуры текста и /edit для редактирования. Отправьте одну из этих команд, я подскажу, как действовать дальше.

Если что-то пошло не так, напишите нам: no.more.spelling.errors@gmail.com

***

#### Текст повторной оплаты

Ой, что-то пошло не так: оплата не удалась :(

Возможные причины:
— недостаточно средств;
— действуют ограничения вашего банка;
— неверно введены реквизиты.

Пожалуйста, попробуйте еще раз: http://correctarium.com/payment/telegram/4bad2cf830b83ff198fe331478283be3

**Comment by terales** [comment]
Правильно ли я понимаю, что текст заказа нужно предварять символом «>»?

**Comment by butkam** [comment]
@terales нет, это форматирование github, чтобы понимать, что это не часть текста. Текста заказа просто с нового абзаца.

**Comment by terales** [comment]
Принято.

**Comment by butkam** [comment]
Прошу сохранить форматирование текста (переносы строк, символы).
