### ISSUE TITLE
Изучить вопрос большого количества символов в заказе (более 4069)

### ISSUE THREAD

**Issue by butkam** [nomorespellingerrors/teledit#16]
Если в заказе больше 4069 символов, Телеграм делит сообщение на несколько отдельных.

Проблема:
При большом заказе, на каждое такое сообщение при ходит ссылка на оплату.

Решение:
— объединить и сгенерировать одну ссылку,
— работа с файлами.

**Comment by butkam** [comment]
Возможно не обрабатывать пока большие тексты, отвечать: К сожаления я не могу обрабатывать на столько длинные тексты, но мои люди с удовольствием вам помогут. Отправьте текст на no.more.spelling.errors@gmail.com

Или отправлять этот текст на имейл автоматически и отвечать: К сожаления я пока не умею обрабатывать большие объемы текста. Я отправил этот текст людям, они свяжутся с вами и выполнят работу.

**Comment by terales** [comment]
> объединить и сгенерировать одну ссылку

Я думаю у меня получится это сделать уже сейчас, а вот для работы с файлами завел новый тикет #17

**Comment by terales** [comment]
Провел несколько испытаний — по-простому решить вопрос не получается. Основная загвоздка в понимании — это конкретное сообщение это весь заказ или только его первая часть. Значит ни собрать текст в одну квоту, ни даже выдать осмысленную ошибку не смогу. Предлагаю:

* в ответы на команды `/proof` и  `/edit` добавить фразу вроде: «… Если Ваш текст больше 2 страниц (4 тыс. символов), то отправьте его на no.more.spelling.errors@gmail.com».
* в тексте ошибки при получении текста после выставления offer писать: «К сожаления я не могу обрабатывать настолько длинные тексты, но мои люди с удовольствием вам помогут. Отправьте текст на no.more.spelling.errors@gmail.com»

Антон, принимаешь?

**Comment by butkam** [comment]
Да, хорошо.
