### ISSUE TITLE
Непонятно как работаем с командой /delivery

### ISSUE THREAD

**Issue by butkam** [nomorespellingerrors/teledit#3]
Чтобы отправить заказ ответьте на сообщение бота готовым текстом.

**Comment by terales** [comment]
Добавить отдельный текст ошибки для группы менеджеров с дополнительным текстом: «чтобы отправить заказ ответьте на сообщение бота готовым текстом.»

**Comment by butkam** [comment]
Добавили задачу, в которой есть готовый текст для ошибки: https://github.com/nomorespellingerrors/teledit/issues/12

**Comment by butkam** [comment]
@terales эта задача не в приоритете, пока мы будем управлять распределением заказов.
