### ISSUE TITLE
Бот отвечает ошибкой на команду /start

### ISSUE THREAD

**Issue by butkam** [nomorespellingerrors/teledit#4]
1. Пригласил бота в группу,
2. Бот ответил Простите я вас не понял,

Нужно, чтобы он отвечал приветствием.

![screen shot 2015-11-09 at 09 40 37](https://cloud.githubusercontent.com/assets/1357343/11029242/fba9b742-86c5-11e5-82d0-8f6467ae89e3.png)

**Comment by terales** [comment]
Протестировал:

1. Если это было в группе, то исправлено в #6 
2. Если это было при очистке и создании конфиденциального чата заново, то у мнея не получилось воспроизвести ни в моем аккаунте, ни в специально созданном новом.

Антон, ты тестировал именно в группе, верно?

**Comment by butkam** [comment]
На /start он у меня (и не только у меня) отвечал ошибкой везде. Теперь не повторяется.
