### ISSUE TITLE
Отменять заказ, если человек долго не отвечает на сообщение бота

### ISSUE THREAD

**Issue by butkam** [nomorespellingerrors/teledit#5]
Проблема выглядит так, что если человек передумал или ошибся с командой или текстом, он не может начать все заново.

![screen shot 2015-11-09 at 09 52 46](https://cloud.githubusercontent.com/assets/1357343/11029607/63c3e972-86c8-11e5-939f-a024c7a05ac2.png)

**Comment by terales** [comment]
Не получилось воспроизвести, возможно, это была проблема из-за отсутствия веб-хуков? Или очень уж тормозил телеграмм? :alien: 

![issue-5](https://cloud.githubusercontent.com/assets/1920639/11168929/72a2ac46-8bad-11e5-905e-6d6c07dc293d.png)

Сейчас вроде все ок, можешь подтвердить? Пока закрываю.

**Comment by butkam** [comment]
Да, сейчас все работает корректно.
