### ISSUE TITLE
Бот неработает в группе с клиентом

### ISSUE THREAD

**Issue by butkam** [nomorespellingerrors/teledit#6]
Скриншот сделан в группе, в которую был приглашен бот. У одного из пользователей бота в друзьях до этого не было.

![713313500_1320785789009492362](https://cloud.githubusercontent.com/assets/1357343/11030928/769386b2-86d1-11e5-989e-e48cea7f860b.jpg)

**Comment by butkam** [comment]
Позже уточню детали.

**Comment by terales** [comment]
Согласно документации, такая форма комманд используется когда в одной группе есть несколько ботов: https://core.telegram.org/bots#commands

Кстати, обработку комманд такого рода я не добавлял.

**Comment by terales** [comment]
- [ ] Добавить обработку комманд с обращением к боту по имени (@)
- [ ] Протестировать процесс заказа из группы (предполагаю, что может быть затык в получении текста заказа из-за ограничений режима конфиденциальности)

**Comment by butkam** [comment]
@terales это дубликат уже сделанной задачи получается?

**Comment by terales** [comment]
> это дубликат уже сделанной задачи получается?

Перовоначально — да, это дубликат (хотя эта задача была создана раньше и формально #14 дубликат).

Но, пока анализировал документацию API связанную с твоим сообщением, я увидел пробел тестирования бота в «клиентских» группах. 

Уже начал тестировать и править бота.

**Comment by terales** [comment]
@butkam работа с ботом в группе чуть отличается от конфиденциального чата — чтобы передать текст заказа нужно отвечать на сообщение бота. Чтобы сделать это прозрачнее для пользователей я создал отдельные шаблоны сообщений:

* [2usergroup_edit.txt](https://github.com/nomorespellingerrors/teledit/blob/master/messages/2usergroup_edit.txt)
* [2usergroup_proof.txt](https://github.com/nomorespellingerrors/teledit/blob/master/messages/2usergroup_proof.txt)

**Comment by butkam** [comment]
Да, все окей, это было в группе, теперь работает.
