### ISSUE TITLE
Добавить учет дня и ночи в расчет срока

### ISSUE THREAD

**Issue by terales** [nomorespellingerrors/teledit#8]
@butkam Какое действует правило расчета и отображения?

**Comment by butkam** [comment]
@terales если дедлайн (время сдачи заказа) больше 23:00 заказ переносится на следующий день и отчет стартует с 10:00 по Киевскому времени.

**Comment by terales** [comment]
Правила противоречат друг другу:

* если дедлайн после 23:00 по киеву — заказ переносится на следующий день (здесь ясно);
* если заказ на пересечении… **дедлайн в 00:30** — значит здесь срабатывает первое правило.

Возможно ты хотел сказать такое правило:

1. Если offer генерируется после 23 часов по Киеву — показываем время сдачи не в формате «через ХХ минут», а в формате «завтра к ЧЧ:ММ» с началом отсчета с 10 часов по Киеву.
2. Если offer генерируется до 23 часов, но время сдачи позже 23 — время до 23 часов учитываем в день заказа, а остаток добавляем к 10 часам следующего дня.

Я правильно пересказал твое намерение?

**Comment by butkam** [comment]
Надеюсь так будет более понятно.

Красный — срок заказа, черный — сутки.

![fullsizerender 3](https://cloud.githubusercontent.com/assets/1357343/11059497/640c874a-879a-11e5-9136-e66db62c3335.jpg)

**Comment by butkam** [comment]
Да, ты все правильно понял. Если можно считать не в минутах а переводить в часы, если заказ больше 60 минут — писать 1 час, 1 час 30 мин и т. д. Если нет, оставляем в минутах.

**Comment by terales** [comment]
> Надеюсь так будет более понятно.

да, стильно рисуешь :+1: 

> Если можно считать не в минутах а переводить в часы, если заказ больше 60 минут — писать 1 час, 1 час 30 мин и т. д. Если нет, оставляем в минутах.

Можно, сделаю. Только согласно #12 будет: 1 час, 1 час 30 мин**ут**…

**Comment by butkam** [comment]
> Можно, сделаю. Только согласно #12 будет: 1 час, 1 час 30 минут…

Хорошо.

**Comment by terales** [comment]
Посмотрел внимательнее — согласно #12 есть два варианта использования этой строки:

* «…мы выполним ваш заказ в течение **25 минут** после оплаты заказа.» — здесь 1 час нужно написать как «…в течение 1 часа…»
* Нужно сдать через 25 минут — здесь 1 час нужно так и оставить.

Выходит, мне нужно будет проработать единичное и множественное значение слова «час» в двух разных падежах.

Можно ли сменить текст, который мы шлем Менеджеру на такой:

> …
> Нужно сдать **в течении** 25 минут
> …

**Comment by terales** [comment]
Другой вопрос. Какое писать сообщение если у нас был перенос на следующий день? Такое?

> …мы выполним ваш заказ **16 ноября к 10:30 если оплатите сейчас**.

И сразу хочу согласовать сообщение Менеджеру:

> …
> Нужно сдать **16 ноября к 10:30**
> …

**Comment by butkam** [comment]
> Можно ли сменить текст, который мы шлем Менеджеру на такой:

Да, конечно можно. Текст подходит.

> Другой вопрос. Какое писать сообщение если у нас был перенос на следующий день? Такое?

Давай просто: мы выполним этот заказ 16 ноября к 10:30.

> И сразу хочу согласовать сообщение Менеджеру:

Да, все верно.

**Comment by terales** [comment]
Принято.
